export const SearchViewExtractRequest =
{
  "RequestType": "UIQUERY",
  "UserParams": [
    {
      "UserID": "test@vodafone.com",
      "Destination": "DCM"
    }
  ],
  "RequestParams": [
    {
      "ReportIdenitifer": "SearchViewExtract",
      "SubReportName": "",
      "RecordIdentifier": "number_range"
    }
  ],
  "Data": [
    {
      "number_range": "1234",
      "number_range_type": "GEO",
      "pagenumber": "1"
    }
  ]
}
// {
// 	"RequestType": "QUERY",
// 	"UserParams": [{
// 		"UserID": "DCMAdmin",
// 		"Destination": "DCM"
// 	}],
// 	"RequestParams": [{
// 		"ReportIdenitifer": "SearchViewExtract",
// 		"SubReportName": ""
// 	}],
// "PyRequest":
// {
//   "QueryObjectRequest" : {
//     "QueryObjectRequestType" : {
//       "RequestIdentifiers" : {
//         "Identifier" : [ {
//           "Name" : "UserId",
//           "Value" : [ "DCMAdmin" ]
//         }, {
//           "Name" : "Destination",
//           "Value" : [ "DCM" ]
//         } ]
//       },
//       "ListofQueryObjectCategory" : {
//         "QueryObjectCategory" : [ {
//           "ItemName" : "",
//           "ListofIdentifiers" : {
//             "Identifier" : [ {
//               "Name" : "ReportIdentifier",
//               "Value" : [ "number_range" ]
//             } ]
//           },
//           "ListofQueryObjectCharacteristics" : {
//             "QueryObjectCharacteristics" : [ {
//               "ItemName" : "QueryParameters",
//               "ListofIdentifiers" : {
//                 "Identifier" : [ {
//                   "Name" : "number_range",
//                   "Value" : [ "1234" ]
//                 }, {
//                   "Name" : "number_range_type",
//                   "Value" : [ "GEO" ]
//                 },  {
//                   "Name" : "PageNumber",
//                   "Value" : [ "1" ]
//                 } ]
//               }
//             } ]
//           }
//         } ]
//       }
//     }
//   }
// }
// }


export const SearchViewExtractResponse =
{
  "Response": "UIQUERY",
  "Status": [
    {
      "StatusCode": "PY1000",
      "StatusMessage": "Success",
      "MessageType": "Informational"
    }
  ],
  "ResponseParams": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "DCMAdmin",
    "RecordIdentifier": "number_range"
  },
  "Data": [
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    },
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    }, {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    }
  ]
}

export const NGNSearch: any = {
  "GEO":{ "params": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "test@vodafone.com",
    "RecordIdentifier": "SearchViewExtract",
    "TotalCount":"3"
},
    "data": [
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    }
  ]},
  "INTERNATIONAL": { "params": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "test@vodafone.com",
    "RecordIdentifier": "SearchViewExtract",
    "TotalCount":"3"
},
"data": [
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
  ]},
  "NGN": { "params": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "test@vodafone.com",
    "RecordIdentifier": "SearchViewExtract",
    "TotalCount":"3"
}, 
"data": [
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    }
  ]},
  "OFCOM":{ "params": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "test@vodafone.com",
    "RecordIdentifier": "SearchViewExtract",
    "TotalCount":"5"
}, 
"data":[
    { nms_number_block: "Test", block_status: "Test", cp_name: "Test", number_length: "Test", allocation_date: "Test", notes: "Test"},
    { nms_number_block: "Test1", block_status: "Test1", cp_name: "Test1", number_length: "Test1", allocation_date: "Test1", notes: "Test1"},
    { nms_number_block: "Test2", block_status: "Test2", cp_name: "Test2", number_length: "Test2", allocation_date: "Test2", notes: "Test2"},
    { nms_number_block: "Test3", block_status: "Test3", cp_name: "Test3", number_length: "Test3", allocation_date: "Test3", notes: "Test3"},
    { nms_number_block: "Test4", block_status: "Test4", cp_name: "Test4", number_length: "Test4", allocation_date: "Test4", notes: "Test4"}
  ]}
  ,
  "ALL":{ "params": {
    "ReportIdenitifer": "SearchViewExtract",
    "SubReportName": "SearchViewExtract",
    "UserId": "test@vodafone.com",
    "RecordIdentifier": "SearchViewExtract",
    "TotalCount":"9"
},
"data": [
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    },
    {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    }, {
      "number_range": "1234567892",
      "number_range_type": "INT",
      "number_range_start_date": "2022/12/29",
      "number_range_stop_date": "2022/12/30",
      "number_range_owner_id": "612",
      "number_range_owner_name": "Mixed",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "VCSRATES"
    },
    {
      "number_range": "01130",
      "number_range_type": "GEO",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "12/30/2022",
      "number_range_owner_id": "1",
      "number_range_owner_name": "BT - DLE",
      "host_name": "12.122",
      "gen_description": "BT - DLE",
      "bt_charge_band_code": "123",
      "cost_category": "OX",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "LCR"
    },
    {
      "number_range": "12345",
      "number_range_type": "NGN",
      "number_range_start_date": "12/29/2022",
      "number_range_stop_date": "",
      "number_range_owner_id": "23",
      "number_range_owner_name": "AA",
      "host_name": "12.122",
      "gen_description": "DES",
      "bt_charge_band_code": "123",
      "cost_category": "123",
      "rounding_rule": "123",
      "rounding_rule_description": "ASDE",
      "threshold": "22",
      "service_description": "SERDC",
      "origin_based_rating": "23",
      "traffic_type": "RE",
      "itct_rating_type": "TE",
      "country_name": "UK",
      "country_iso_code": "12E",
      "country_idd_code": "12E",
      "source_system": "SASS"
    }
  ]
}
}