export interface liverecords {
    // TranId: string;
    // View: string;
    // TelNo: string;
    // Cmd: string;
    // Source: string;
    // Created: string;
    // Ovd: string;
    // Status: string;
    // ResType: string;
    // ErrorList: string;
Links :string;
Telephone:string;
CustName:string;
BusinessSuffix :string;
Premises:string;
Thoroughfare:string;
Locality:string;
Createdby:string;
CreationDate:string;
Postcode:string;
TransactionRef:string;
CustTitle:string;
CustForename:string;
Franchise:string;
SourceSystem:string;
SourceType:string;
AddressLine1:string;
AddressLine2:string;
AddressLine3:string;
AddressLine4:string;
ParentCUPID:string;
ChildCUPID:string;
RetailerID:string;
NewTelNo:string;
CrossRefNo:string; 
LineType:string;
AddrId:string;
AddrIdSource:string;
TypeofLine:string;
}